name: Order API CI

on:
  push:
    branches:
      - main
      - stg

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:

  build-and-push:
    uses: abdosaad203/reusable-backend-ci/.github/workflows/backend-ci.yml@main

    secrets: inherit

    with:
      dotnet-version: '10.0.x'
      project-path: 'Order.API/Order.API.csproj'
      test-path: 'Order.API.Tests/Order.API.Tests.csproj'
      run-tests: true
      image-name: 'order-api'

  deploy-staging:
    needs: build-and-push

    if: github.ref == 'refs/heads/stg'

    runs-on: ubuntu-latest

    steps:
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: abdosaad203/ecommerce-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update staging image tag
        run: |
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" gitops/environments/stg/order-api.yaml

      - name: Commit and push
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "update order-api staging image to ${IMAGE_TAG}" || echo "No changes"

          git push

  deploy-production:
    needs: build-and-push

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: abdosaad203/ecommerce-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update production image tag
        run: |
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" gitops/environments/prod/order-api.yaml

      - name: Commit and push
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "update order-api production image to ${IMAGE_TAG}" || echo "No changes"

          git push